### ISSUE TITLE
Who?

### ISSUE THREAD

**Issue by GabrielWeinbrenner** [HackRU/Reactment#150]
Create a dynamic route (/person/{name}) that when routed to will display a page that greets the user with their name and "profile". In addition to their name, you will also add different random details of their life from an api: https://randomuser.me/api/. These pages should mimic a social media like profile page.

**Comment by ethxng** [comment]
I assigned myself this issue

**Comment by andrewhong04** [comment]
I can do this.

**Comment by kevinmonisit** [comment]
no u cant
