### ISSUE TITLE
(2) Troll the User

### ISSUE THREAD

**Issue by bhivam** [HackRU/Reactment#172]
Have the chatbot on the “Contact Us” send one of three random unhelpful messages and send a troll face to the user after the unhelpful message.

**Comment by dgc86** [comment]
I wanted to select this issue but I wanted to know if the unhelpful message would be sent after the user asks a question.

**Comment by bhivam** [comment]
> I wanted to select this issue but I wanted to know if the unhelpful message would be sent after the user asks a question.

Yeah, any time the user sends to the chatbot, give the unhelpful response as specified.
