### ISSUE TITLE
(3) Better Announcements

### ISSUE THREAD

**Issue by bhivam** [HackRU/Reactment#174]
The Announcement page could use some revamping. Put each announcement in a box with a max width for screens with large a aspect ratio. Make a section for the time of the message and another for the message itself. Remove any commands ( stuff in this format: <!command-name>) and make the links (stuff in this format: <link>) work.

**Comment by utkarshdubey** [comment]
This task seems to be broken, the API endpoint (https://api.hackru.org/prod/dayof-slack) is throwing errors/stale responses.
