### ISSUE TITLE
(3) Choose Your Pokemon!

### ISSUE THREAD

**Issue by bhivam** [HackRU/Reactment#175]
Create a button on the homepage where you can enter a Pokemon name and click a button to “get info” about the Pokemon. Display the information in the table below. Use the pokeapi: https://pokeapi.co/api/v2/pokemon/<pokemon-name>. Make an error pop up if the name the user's entry is invalid.

**Comment by utkarshdubey** [comment]
Not sure if I have the permissions to assign myself to this, I'm just creating a PR instead.
