### ISSUE TITLE
(2) Center We Go!

### ISSUE THREAD

**Issue by shivanmodha** [HackRU/Reactment#2]
## Description
`Level 2`
> Center the text vertically on the page.

**Comment by zain08816** [comment]
Removed myself issue since I had already assigned myself to Issue #5 . I am not planning on doing a PR for this issue and will leave it open for anyone else do to complete if they choose this one.

**Comment by mjrb** [comment]
this issue may not make sense anymore since there is a lot of content on the home page. but #45 may fix this

**Comment by shivanmodha** [comment]
Yeah this doesn't make sense anymore, I'm gonna close this out.
