### ISSUE TITLE
Who chose the background color?

### ISSUE THREAD

**Issue by kevinmonisit** [HackRU/Reactment#204]
hola que tal mi gente 

We have an ugly background color. (My favorite color is orange..... but not this orange).

Could you not only change it, but change it to something thats animated and doesn't obscure the text? (maybe an animated gradient? or animated effect? whatever makes u happy)

For example, don't just make the background a dark color all the way because then the black text will not be seen (unless you have a neat design solution for that.... then go on ahead)

muchas gracias amigos

ciao ciao

**Comment by Hetp29** [comment]
I self-assign this task.
