### ISSUE TITLE
(3) Improved Nav

### ISSUE THREAD

**Issue by mjrb** [HackRU/Reactment#25]
## Description
`Level 3`
> Now that we have an improved nav bar, let's put it to work
- [x] add a callback to the constructor of the `Navbar` component to notify the parent component when the user selects a different page
- [x] add state to the app component to display different content when the user selects a different option on the nav bar
>All current contend should be considered part of the home page, and the home page should be the default one

**Comment by benlambert43** [comment]
For the Router function that contains a switch statement in the App component, I would normally create a new custom component for each page in the router so there is less repeated code and pass in props based on what that component needs. Let me know if you want me to do this
