### ISSUE TITLE
(1) Helpless users

### ISSUE THREAD

**Issue by mjrb** [HackRU/Reactment#29]
## Description
`Level 1`
> Add a help button for confused users. don't connect it to anything, because we don't have enough money in the budget to actually help them. Extra points if you can figure out whatever the opposite of help would be in this context.

**Comment by JasonCheng1** [comment]
Would the opposite of a help button be a report/feedback button?

**Comment by mjrb** [comment]
good idea, but reporting/feedback would actually do something helpful potentially.
