### ISSUE TITLE
(2) Cash Rules Everything Around Me

### ISSUE THREAD

**Issue by mjrb** [HackRU/Reactment#31]
## Description
`Level 2`
> Monetize this app! add a side bar to display whatever add you want on the side (keep it pg13). bonus points if you can get it to pick a random add from a handfull

**Comment by skad2198** [comment]
unassigned myself for now, open for anyone else to take..

**Comment by mjrb** [comment]
@v0lv0 if you are finished with this issue, please push your code and open a pull request and then we can close it once the pull request is accepted

**Comment by lucentfong** [comment]
Love the ads you decided to put in!
