### ISSUE TITLE
(3) (Ab)using our backend

### ISSUE THREAD

**Issue by mjrb** [HackRU/Reactment#48]
## Description
`Level 3`
> let's spice up this website's homepage by listing out hackru announcements from slack. using the js `fetch` function you can get some public anouncements from our backend using the url `https://api.hackru.org/prod/dayof-slack`. if you just go to that url in your browser you can see what the data looks like. __important__ make sure you only call fetch when a component is initialized using a react stateful component or useState hook. this ensures there aren't excessive requests when the page is updated, like when you use the "log me" button

**Comment by JScheire** [comment]
Going to assign myself this once I get added to the repo as a contributor.

**Comment by mjrb** [comment]
there should be a separate email from github inviting you as a contributor. i sent it before i emailed you, but i can send it again if you want

**Comment by JScheire** [comment]
Got it!

**Comment by mjrb** [comment]
closed by #68
