### ISSUE TITLE
(3) talk to me

### ISSUE THREAD

**Issue by mjrb** [HackRU/Reactment#49]
## Description
`Level 3`
> add a fake live chatbox to the contact us page. the ai behind this will be highly sophisticated: whenever the user asks the bot a question it will always respond with "I didn't quite understand that, please try rephrasing what you said." you will need to create a chatbox component that is either a react stateful component, or uses the `useState` react hook. it should list out all the messages from the user and the "bot", have a text input for the user to type a message, and a send button that "sends" the message. this one is a bit complicated so feel free to ask lots of questions

**Comment by foltik** [comment]
@mjrb If I already did an issue back in January should I hold off on doing any more?

**Comment by mjrb** [comment]
@Foltik the short answer is no. please email us about this, i think something slipped though the cracks, but we'd still love to have you on the team. its just this isn't strictly related to this issue
