### ISSUE TITLE
(2) Bland Brand Land

### ISSUE THREAD

**Issue by lucentfong** [HackRU/Reactment#54]
**Description**
Level 2
Display the HackRU logo in a header above the Navbar. Add an animation to it when you load the page!

**Comment by mjrb** [comment]
@JonCanales  I appreciate you enjoying playing with this and doing multiple issues, but if you want we can leave some for other people to complete so we don't have to add more. you can unassign yourself from this unless you really want to do it

**Comment by JonCanales** [comment]
Of course! I didn't know if we just had to do one or several. I got really
into it and doing the issues was fun for me. I will assign myself from this
issue. Sorry for the inconvenience!

**Comment by mjrb** [comment]
np, its really cool to see people having fun with this
