### ISSUE TITLE
(3) Fresh Tomatoes

### ISSUE THREAD

**Issue by lucentfong** [HackRU/Reactment#58]
**Description**
Level 3
In the Contact Us page, add a way for users to rate their experience out of 5 (1 being worst, 5 being best). Take the average of these ratings and find a way to display it graphically. This graphic should be modified every time the average changes. If our average rating is above 4.2, then our website is certified fresh. Find a way to make our users know if we’re certified fresh!

**Comment by mjrb** [comment]
@GabrielWeinbrenner I appreciate you enjoying playing with this and doing multiple issues, but if you want we can leave some for other people to complete so we don't have to add more. you can unassign yourself from this unless you really want to do it

**Comment by GabrielWeinbrenner** [comment]
@mjrb Sorry I will unassign myself from this issue.
