### ISSUE TITLE
(3) Contraction Contraption

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/Reactment#83]
**Description**

Write a UI that takes a text sentence as a string and returns a string with all the contractions instead (ie. "is not" becomes "isn't"). Convert at least [should, could, would, do, is, are, does, have] not => []n't and [should, could, would] have => []'ve. Many may occur in a sentence. Words will be delimited by single spaces and will not contain punctuation.

**Trivia**

This is actually the first ever RnD interview question! The interview process was very different, so the above is a shorter version of the question. The whole question was:

1. Write a function that takes a sentence as a string and returns a string with all the contractions instead (ie. "is not" becomes "isn't"). Convert at least [should, could, would, do, is, are, does, have] not => []n't and [should, could, would] have => []'ve. Many may occur in a sentence. Words will be delimited by single spaces and will not contain punctuation.
2. Multiple contractions can be chained in some cases: there's a famous Southern "y'all'd've" (you all would have) which y'all'd'ven't (you all would have not) heard of if y'all'evn't (you all have not (I may be making this one up)) been to the South. Additionally, Scottish slang allows for "am not" to be written as "amn't," which ain't different from "ain't." Design an app to let users input sentences and get shortened (or even expanded) ones back. How would you allow them to conveniently configure your tool to handle all sorts of contractions (even their own, or their own odd chains)?

**Comment by kevinmonisit** [comment]
Hey, I'd like to assign myself to this issue but it seems like I can't.

**Comment by lucentfong** [comment]
Hi Kevin, try assigning yourself the issue now - I forgot to give Triage permissions to applicants.
